/// Fill out your copyright notice in the Description page of Project Settings.


#include "Player/ActionCharacter.h"
#include "EnhancedInputComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Camera/CameraComponent.h"
#include "Player/ResourceComponent.h"
#include "Weapon/WeaponActor.h"
#include "Weapon/WeaponPickUp.h"
#include "StatusComponent.h"

// Sets default values
AActionCharacter::AActionCharacter()
{
	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.bStartWithTickEnabled = true;
	SetActorTickEnabled(true);

	SpringArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm"));
	SpringArm->SetupAttachment(RootComponent);
	SpringArm->TargetArmLength = 350.0f;
	SpringArm->SocketOffset = FVector(0, 0, 250);
	SpringArm->bUsePawnControlRotation = true;	// ìŠ¤í”„ë§ì•”ì˜ íšŒì „ì„ ì»¨íŠ¸ë¡¤ëŸ¬ì— ë§ì¶¤

	PlayerCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("PlayerCamera"));
	PlayerCamera->SetupAttachment(SpringArm);
	PlayerCamera->SetRelativeRotation(FRotator(-20.0f, 0.0f, 0.0f));

	Resource = CreateDefaultSubobject<UResourceComponent>(TEXT("PlayerResource"));

	bUseControllerRotationYaw = false;	// ì»¨íŠ¸ë¡¤ëŸ¬ì˜ Yaw íšŒì „ ì‚¬ìš© ì•ˆí•¨
	GetCharacterMovement()->bOrientRotationToMovement = true;	// ì´ë™ ë°©í–¥ìœ¼ë¡œ ìºë¦­í„° íšŒì „
	GetCharacterMovement()->RotationRate = FRotator(0, 360, 0);

	Status = CreateDefaultSubobject<UStatusComponent>(TEXT("StatusComponent"));
}

// Called when the game starts or when spawned
void AActionCharacter::BeginPlay()
{
	Super::BeginPlay();



	if (GetMesh())
	{
		AnimInstance = GetMesh()->GetAnimInstance();	// ABP ê°ì²´ ê°€ì ¸ì˜¤ê¸°
	}
	if (Resource)
	{
		Resource->OnStaminaEmpty.AddDynamic(this, &AActionCharacter::SetWalkMode);
	}

	// ê²Œì„ ì§„í–‰ ì¤‘ì— ìì£¼ ë³€ê²½ë˜ëŠ” ê°’ì€ ì‹œì‘ ì‹œì ì—ì„œ ë¦¬ì…‹ì„ í•´ì£¼ëŠ” ê²ƒì´ ì¢‹ë‹¤.
	bIsSprint = false;
	if (WeaponClass)	// UPROPERTY(EditAnywhere) TSubclassOf<AWeaponActor> WeaponClass; ë¼ê³  ê°€ì •
	{
		FActorSpawnParameters Params;
		Params.Owner = this;
		Params.Instigator = this;

		AWeaponActor* NewWeapon = GetWorld()->SpawnActor<AWeaponActor>(
			WeaponClass,
			FVector::ZeroVector,
			FRotator::ZeroRotator,
			Params);

		if (NewWeapon)
		{
			// hand_r_Socket ì— ë¶™ì´ê¸° (ë©”ì‰¬ì— ë¯¸ë¦¬ ì†Œì¼“ ë§Œë“¤ì–´ ë†”ì•¼ í•¨)
			FAttachmentTransformRules Rules(
				EAttachmentRule::SnapToTarget,
				EAttachmentRule::SnapToTarget,
				EAttachmentRule::SnapToTarget,
				true);

			NewWeapon->AttachToComponent(
				GetMesh(),
				Rules,
				TEXT("hand_r_Socket")); // ì†Œì¼“ ì´ë¦„

			// ì„œë¡œ ì°¸ì¡° ì—°ê²°
			CurrentWeapon = NewWeapon;        // TWeakObjectPtr<AWeaponActor> ë¼ê³  ê°€ì •
			NewWeapon->SetWeaponOwner(this);    // WeaponActor.h ì— TWeakObjectPtr<AActionCharacter> WeaponOwner; ìˆë‹¤ê³  ê°€ì •

			BaseWeapon = CurrentWeapon;
			EnhancedWeapon = nullptr;
			bUsingEnhancedWeapon = false;
			EnhancedMaxUses = 0;
			EnhancedRemainingUses = 0;
		}
	}

}

// Called every frame
void AActionCharacter::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	SpendRunStamina(DeltaTime);
}

// Called to bind functionality to input
void AActionCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	UEnhancedInputComponent* enhanced = Cast<UEnhancedInputComponent>(PlayerInputComponent);
	if (enhanced)	// ì…ë ¥ ì»´í¬ë„ŒíŠ¸ê°€ í–¥ìƒëœ ì…ë ¥ ì»´í¬ë„ŒíŠ¸ì¼ ë•Œ
	{
		enhanced->BindAction(IA_Move, ETriggerEvent::Triggered, this, &AActionCharacter::OnMoveInput);
		enhanced->BindActionValueLambda(IA_Sprint, ETriggerEvent::Started,
			[this](const FInputActionValue& _) {
				SetSprintMode();
			});
		enhanced->BindActionValueLambda(IA_Sprint, ETriggerEvent::Completed,
			[this](const FInputActionValue& _) {
				SetWalkMode();
			});
		enhanced->BindAction(IA_Roll, ETriggerEvent::Triggered, this, &AActionCharacter::OnRollInput);
		enhanced->BindAction(IA_Attack, ETriggerEvent::Triggered, this, &AActionCharacter::OnAttackInput);
		if (IA_DropItem)
		{
			enhanced->BindAction(IA_DropItem, ETriggerEvent::Started, this, &AActionCharacter::DropWeapon);
		}
		else
		{
			UE_LOG(LogTemp, Warning, TEXT("IA_DropItem ì´ BPì—ì„œ ì„¤ì • ì•ˆ ë˜ì–´ ìˆìŒ"));
		}
	}
	
}

void AActionCharacter::OnAttackEnable(bool bEnable)
{
	
	if (CurrentWeapon)
	{
		CurrentWeapon->AttackEnable(bEnable);
	}
	
	UE_LOG(LogTemp, Warning, TEXT("OnAttackEnable: %s"), bEnable ? TEXT("True") : TEXT("False"));

	if (bEnable)
	{
		ConsumeEnhancedWeaponUse();
	}
}

void AActionCharacter::OnMoveInput(const FInputActionValue& InValue)
{
	FVector2D inputDirection = InValue.Get<FVector2D>();
	//UE_LOG(LogTemp, Log, TEXT("Dir : (%.1f, %.1f)"), inputDirection.X, inputDirection.Y);
	//UE_LOG(LogTemp, Log, TEXT("Dir : (%s)"), *inputDirection.ToString());
	FVector moveDirection(inputDirection.Y, inputDirection.X, 0.0f);

	FQuat controlYawRotation = FQuat(FRotator(0, GetControlRotation().Yaw, 0));	// ì»¨íŠ¸ë¡¤ëŸ¬ì˜ YawíšŒì „ì„ ë”°ë¡œ ë½‘ì•„ì™€ì„œ
	moveDirection = controlYawRotation.RotateVector(moveDirection);	// ì´ë™ ë°©í–¥ì— ì ìš©

	AddMovementInput(moveDirection);

}

void AActionCharacter::OnRollInput(const FInputActionValue& InValue)
{
	if (AnimInstance.IsValid())
	{
		if (!AnimInstance->IsAnyMontagePlaying()
			&& Resource->HasEnoughStamina(RollStaminaCost))	// ëª½íƒ€ì£¼ ì¬ìƒì¤‘ì´ ì•„ë‹ˆê³  ì¶©ë¶„í•œ ìŠ¤íƒœë¯¸ë„ˆê°€ ìˆì„ ë•Œë§Œ ì‘ë™
		{
			//if (!GetLastMovementInputVector().IsNearlyZero())	// ì…ë ¥ì„ í•˜ëŠ” ì¤‘ì—ë§Œ ì¦‰ì‹œ íšŒì „
			//{
			//	SetActorRotation(GetLastMovementInputVector().Rotation());	// ë§ˆì§€ë§‰ ì…ë ¥ ë°©í–¥ìœ¼ë¡œ ì¦‰ì‹œ íšŒì „ ì‹œí‚¤ê¸°
			//}
			Resource->AddStamina(-RollStaminaCost);	// ìŠ¤íƒœë¯¸ë„ˆ ê°ì†Œ
			PlayAnimMontage(RollMontage);
		}
	}
}

void AActionCharacter::OnAttackInput(const FInputActionValue& InValue)
{
	if (AnimInstance.IsValid() && Resource->HasEnoughStamina(AttackStaminaCost)) // ì• ë‹˜ ì¸ìŠ¤í„´ìŠ¤ê°€ ìˆê³  ìŠ¤íƒœë¯¸ë„ˆë„ ì¶©ë¶„í•  ë•Œ
	{
		if (!AnimInstance->IsAnyMontagePlaying())	// ëª½íƒ€ì£¼ê°€ ì¬ìƒ ì¤‘ì´ ì•„ë‹ ë•Œ
		{
			// ì²«ë²ˆì§¸ ê³µê²©
			PlayAnimMontage(AttackMontage);
			Resource->AddStamina(-AttackStaminaCost);	// ìŠ¤íƒœë¯¸ë„ˆ ê°ì†Œ
		}
		else if (AnimInstance->GetCurrentActiveMontage() == AttackMontage)	// ëª½íƒ€ì£¼ê°€ ì¬ìƒ ì¤‘ì¸ë°, AttackMontageê°€ ì¬ìƒì¤‘ì´ë©´
		{
			// ì½¤ë³´ ê³µê²©
			SectionJumpForCombo();
		}
	}
}

void AActionCharacter::SetSprintMode()
{
	//UE_LOG(LogTemp, Warning, TEXT("ë‹¬ë¦¬ê¸° ëª¨ë“œ"));
	GetCharacterMovement()->MaxWalkSpeed = SprintSpeed;
	bIsSprint = true;
}

void AActionCharacter::SetWalkMode()
{
	//UE_LOG(LogTemp, Warning, TEXT("ê±·ê¸° ëª¨ë“œ"));
	GetCharacterMovement()->MaxWalkSpeed = WalkSpeed;
	bIsSprint = false;
}

void AActionCharacter::SectionJumpForCombo()
{
	if (SectionJumpNotify.IsValid() && bComboReady)	// SectionJumpNotifyê°€ ìˆê³  ì½¤ë³´ê°€ ê°€ëŠ¥í•œ ìƒíƒœì´ë©´
	{
		UAnimMontage* current = AnimInstance->GetCurrentActiveMontage();
		AnimInstance->Montage_SetNextSection(					// ë‹¤ìŒ ì„¹ì…˜ìœ¼ë¡œ ì í”„í•˜ê¸°
			AnimInstance->Montage_GetCurrentSection(current),		// í˜„ì¬ ì„¹ì…˜
			SectionJumpNotify->GetNextSectionName(),				// ë‹¤ìŒ ì„¹ì…˜ì˜ ì´ë¦„
			current);												// ì‹¤í–‰ë  ëª½íƒ€ì£¼

		bComboReady = false;	// ì¤‘ë³µì‹¤í–‰ ë°©ì§€
		Resource->AddStamina(-AttackStaminaCost);	// ìŠ¤íƒœë¯¸ë„ˆ ê°ì†Œ
	}
}

void AActionCharacter::SpendRunStamina(float DeltaTime)
{
	if ((bIsSprint && !GetVelocity().IsNearlyZero())							// ë‹¬ë¦¬ê¸° ìƒíƒœì´ê³  ì›€ì§ì´ì§€ ì•Šê³  ìˆë‹¤.			
		&& (AnimInstance.IsValid() && !AnimInstance->IsAnyMontagePlaying()))	// ì–´ë–¤ ëª½íƒ€ì¥¬ë„ ì¬ìƒì¤‘ì´ì§€ ì•Šë‹¤.(ë£¨íŠ¸ëª¨ì…˜ ë•Œë¬¸ì— Velocity ë³€ê²½ìˆìŒ)
	{
		Resource->AddStamina(-SprintStaminaCost * DeltaTime);	// ìŠ¤íƒœë¯¸ë„ˆ ê°ì†Œ
		//UE_LOG(LogTemp, Log, TEXT("Velocity : %s"), *GetVelocity().ToString());
		//UE_LOG(LogTemp, Warning, TEXT("Stamina : %.1f"), Resource->GetCurrentStamina());
	}

	//GetWorld()->GetFirstPlayerController()->GetHUD();
}

float AActionCharacter::GetAttackPower() 
{
	if (Status)
	{
		return Status->GetAttackPower();
	}
	return 0.0f;
}
void AActionCharacter::OnPickUpEnhancedWeapon(AWeaponPickUp* Pickup)
{
	

	if (!Pickup || !Pickup->WeaponClass)
	{
		UE_LOG(LogTemp, Warning, TEXT("Pickup or WeaponClass is null"));
		return;
	}
	UE_LOG(LogTemp, Warning, TEXT("1"));
	if (!BaseWeapon && CurrentWeapon)
	{
		BaseWeapon = CurrentWeapon;
	}
	if (bUsingEnhancedWeapon && CurrentWeapon && CurrentWeapon != BaseWeapon)
	{
		CurrentWeapon->AttackEnable(false);

		CurrentWeapon->Destroy();
		CurrentWeapon = nullptr;
		bUsingEnhancedWeapon = false;
	}
	
	FActorSpawnParameters Params;
	Params.Owner = this;
	Params.Instigator = this;

	AWeaponActor* NewEnhanced = GetWorld()->SpawnActor<AWeaponActor>(
		Pickup->WeaponClass,
		FVector::ZeroVector,
		FRotator::ZeroRotator,
		Params);

	const FName SocketName = TEXT("hand_r_Socket");

	FAttachmentTransformRules Rules(
		EAttachmentRule::SnapToTarget,
		EAttachmentRule::SnapToTarget,
		EAttachmentRule::SnapToTarget,
		true);
	NewEnhanced->AttachToComponent(GetMesh(), Rules, SocketName);
	NewEnhanced->SetWeaponOwner(this);
	UE_LOG(LogTemp, Warning, TEXT("2"));
	if (BaseWeapon)
	{
		BaseWeapon->SetActorHiddenInGame(true);
		BaseWeapon->SetActorEnableCollision(false);

	}
	UE_LOG(LogTemp, Warning, TEXT("3"));
	EnhancedWeapon = NewEnhanced;
	CurrentWeapon = NewEnhanced;
	bUsingEnhancedWeapon = true;

	if (Pickup->CurrentUses >= 0)
	{
		EnhancedRemainingUses = Pickup->CurrentUses;
	}
	else
	{
		EnhancedRemainingUses = Pickup->MaxUses;
	}
	UE_LOG(LogTemp, Warning, TEXT("Enhanced picked: %s, RemainingUses=%d"),
		*NewEnhanced->GetName(), EnhancedRemainingUses);

	
}
//ê°•í™” ë¬´ê¸° ê³µê²© íšŸìˆ˜ êµ¬í˜„
void AActionCharacter::ConsumeEnhancedWeaponUse()
{
	// í˜„ì¬ ë“¤ê³ ìˆëŠ” ë¬´ê¸°ê°€ ê°•í™” ë¬´ê¸°ê°€ ì•„ë‹ˆë¼ë©´
	if (!bUsingEnhancedWeapon)
	{
		return;
	}
	//ë‚¨ì€ ì‚¬ìš© íšŸìˆ˜ê°€ 0ì´í•˜ë¼ë©´ 
	if (EnhancedRemainingUses <= 0)
	{
		return;
	}
	EnhancedRemainingUses = EnhancedRemainingUses - 1;
	UE_LOG(LogTemp, Warning, TEXT("ê°•í™”ë¬´ê¸° ë‚¨ì€ ê³µê²© íšŸìˆ˜ : %d"), EnhancedRemainingUses);

	// ë‹¤ì¼ìœ¼ë©´ ì´ì œ ê¸°ë³¸ ë¬´ê¸°ë¡œ ê°€ì•¼ì§€
	if (EnhancedRemainingUses <= 0)
	{
		UE_LOG(LogTemp, Warning, TEXT("ê°•í™”ë¬´ê¸° ë‚¨ì€ ê³µê²© íšŸìˆ˜ê°€ ì—†ìŠµë‹ˆë‹¤ : ê¸°ë³¸ë¬´ê¸° ë³€í™˜"));
		if (CurrentWeapon && CurrentWeapon != BaseWeapon)
		{
			CurrentWeapon->AttackEnable(false);
			CurrentWeapon->Destroy();
			CurrentWeapon = nullptr;
		}

		if (BaseWeapon)
		{
			BaseWeapon->SetActorHiddenInGame(false);
			BaseWeapon->SetActorEnableCollision(true);
			CurrentWeapon = BaseWeapon;
		}
		bUsingEnhancedWeapon = false;
		

	}
}

void AActionCharacter::DropWeapon()
{
	UE_LOG(LogTemp, Warning, TEXT("DropWeapon í˜¸ì¶œë¨"));

	// 1) ê°•í™” ë¬´ê¸° ì•ˆ ë“¤ê³  ìˆìœ¼ë©´ ë°”ë¡œ ë¦¬í„´
	if (!bUsingEnhancedWeapon || !EnhancedWeapon)
	{
		UE_LOG(LogTemp, Warning, TEXT("DropWeapon: ê°•í™” ë¬´ê¸° ì—†ìŒ"));
		return;
	}

	// 2) ë“œë¡­ìš© í”½ì—… ë² ì´ìŠ¤ í´ë˜ìŠ¤ ì²´í¬ (BP_WeaponPickUp_Base)
	if (!WeaponPickupClass)
	{
		UE_LOG(LogTemp, Warning, TEXT("DropWeapon: WeaponPickupClass ì—†ìŒ (BPì—ì„œ ì„¤ì • ì•ˆ ë¨)"));
		return;
	}

	// 3) ìŠ¤í° ìœ„ì¹˜: ìºë¦­í„° ì• + ì‚´ì§ ìœ„
	const FVector Forward = GetActorForwardVector();
	const FVector SpawnLocation =
		GetActorLocation()
		+ Forward * 150.0f            // ğŸ‘‰ ì•ìœ¼ë¡œ ë§ì´ ë„ì›Œì„œ ìºë¦­í„°ë‘ ì•ˆ ê²¹ì¹˜ê²Œ
		+ FVector(0.0f, 0.0f, 50.0f); // ìœ„ë¡œ ì¡°ê¸ˆ

	const FRotator SpawnRotation = GetActorRotation();

	FActorSpawnParameters Params;
	Params.Owner = this;

	// 4) í”½ì—… ì•¡í„° ìŠ¤í°
	AWeaponPickUp* DroppedPickup = GetWorld()->SpawnActor<AWeaponPickUp>(
		WeaponPickupClass,
		SpawnLocation,
		SpawnRotation,
		Params
	);

	if (!DroppedPickup)
	{
		UE_LOG(LogTemp, Warning, TEXT("DropWeapon: í”½ì—… ìŠ¤í° ì‹¤íŒ¨"));
		return;
	}
	//ë“œë¡­ì§í›„ ë¬´ê¸°ì„¸íŒ…
	DroppedPickup->WeaponClass = EnhancedWeapon->GetClass();
	DroppedPickup->CurrentUses = EnhancedRemainingUses;

	//ì™¸í˜•ê°±ì‹ 
	DroppedPickup->RefreshVisualFromWeaponClass();

	UE_LOG(LogTemp, Warning, TEXT("DropWeapon: í”½ì—… ìŠ¤í° ì„±ê³µ: %s"), *DroppedPickup->GetName());

	// 5) ì´ í”½ì—…ì´ ì–´ë–¤ ë¬´ê¸°ì¸ì§€ + ë‚¨ì€ ì‚¬ìš©íšŸìˆ˜ ì „ë‹¬
	DroppedPickup->WeaponClass = EnhancedWeapon->GetClass();
	DroppedPickup->CurrentUses = EnhancedRemainingUses;

	UE_LOG(LogTemp, Warning, TEXT("DropWeapon: WeaponClass = %s, Remaining=%d"),
		*EnhancedWeapon->GetClass()->GetName(),
		EnhancedRemainingUses);

	// 6) (ì¼ë‹¨ í…ŒìŠ¤íŠ¸ìš©ìœ¼ë¡œ) ê°•í™”ë¬´ê¸°ë§Œ ì—†ì• ê³ , ê¸°ë³¸ë¬´ê¸°ë¡œ ë³µê·€
	EnhancedWeapon->Destroy();
	EnhancedWeapon = nullptr;
	bUsingEnhancedWeapon = false;
	EnhancedRemainingUses = 0;

	if (BaseWeapon)
	{
		CurrentWeapon = BaseWeapon;
		BaseWeapon->SetActorHiddenInGame(false);
		BaseWeapon->SetActorEnableCollision(false);
	}
	else
	{
		CurrentWeapon = nullptr;
	}

	UE_LOG(LogTemp, Warning, TEXT("DropWeapon: ë“œë¡­ ì™„ë£Œ, ê¸°ë³¸ ë¬´ê¸°ë¡œ ë³µê·€"));
}