// Fill out your copyright notice in the Description page of Project Settings.


#include "Weapon/WeaponPickUp.h"
#include "Components/SkeletalMeshComponent.h"
#include "Components/SphereComponent.h"
#include "Player/ActionCharacter.h"
#include "Weapon/WeaponActor.h"
#include "NiagaraComponent.h"
#include "NiagaraSystem.h"


// Sets default values
AWeaponPickUp::AWeaponPickUp()
{
    PrimaryActorTick.bCanEverTick = true;
    PrimaryActorTick.bStartWithTickEnabled = true;   // ğŸ”¥ ì‹œì‘ë¶€í„° Tick ì¼œê¸°
    SetActorTickEnabled(true);                       // ğŸ”¥ í˜¹ì‹œ ëª¨ë¥´ë‹ˆ ëª…ì‹œì ìœ¼ë¡œ

    PickUpCollision = CreateDefaultSubobject<USphereComponent>(TEXT("PickUpCollision"));
    SetRootComponent(PickUpCollision);

    PickUpMesh = CreateDefaultSubobject<USkeletalMeshComponent>(TEXT("PickUpMesh"));
    PickUpMesh->SetupAttachment(RootComponent);

    PickUpNiagara = CreateDefaultSubobject<UNiagaraComponent>(TEXT("PickUpNiagara"));
    PickUpNiagara->SetupAttachment(PickUpMesh);   // í˜¹ì€ RootComponent
    PickUpNiagara->bAutoActivate = true;
}

void AWeaponPickUp::OnPickupOverlap(
    UPrimitiveComponent* OverlappedComponent,
    AActor* OtherActor,
    UPrimitiveComponent* OtherComp,
    int32 OtherBodyIndex,
    bool bFromSweep,
    const FHitResult& SweepResult
)
{
    
    if (!OtherActor)
    {
        return;
    }

    //ì´ë¯¸ í¡ì…ì¤‘ì¸ì§€ ì²´í¬
    if (bIsAbsorbing)
    {
        if (!TargetCharacter.IsValid())
        {
        return;

        }
    }

    AActionCharacter* ActionChar = Cast<AActionCharacter>(OtherActor);

    if (!ActionChar)
    {
        UE_LOG(LogTemp, Warning, TEXT("ì˜¤ë²„ë ™ í•˜ì§€ë§Œ ì•¡ì…˜ìºë¦­í„°ëŠ” ì•„ë‹˜"));
        return;
    }
    //ì—¬ê¸°ì„œ í¡ì…ëª¨ë“œë¡œ ì „í™˜ì‹œí‚´
    bIsAbsorbing = true;
    TargetCharacter = ActionChar;

    // ì‹œì‘ìœ„ì¹˜ ì €ì¥
    AbsorbStartLocation = GetActorLocation();
    AbsorbElapsedTime = 0.0f;

    //ë”ì´ìƒ ë‹¤ë¥¸ê²ƒê³¼ ê²¹ì¹˜ì§€ ì•Šë„ë¡ ì¶©ëŒ ë”
    if(PickUpCollision)
    {
        PickUpCollision->SetCollisionEnabled(ECollisionEnabled::NoCollision);
        PickUpCollision->SetGenerateOverlapEvents(false);
    }

    UE_LOG(LogTemp, Warning, TEXT("í¡ìˆ˜ í”½ì—… : %s"), *ActionChar->GetName());
    

    RefreshVisualFromWeaponClass();
}


// Called when the game starts or when spawned
void AWeaponPickUp::BeginPlay()
{

	Super::BeginPlay();
    //ì‹œì‘ìœ„ì¹˜ë¥¼ ê²Œì„ì´ ì‹œì‘ë˜ìë§ˆì ì €ì¥ì‹œí‚´
    StartLocation = GetActorLocation();
    //ëŒ€ì¶© ì–´ë”” ë˜ì ¸ë†”ë„ z ì¢Œí‘œë¥¼ 20 ë”í•˜ë‹ˆê¹Œ ëŒ€ì¶© ê·¸ëŸ´ì‹¸í•œ ìœ„ì¹˜ì— ë– ìˆìŒ
    StartLocation.Z = StartLocation.Z + 150.0f;



    UE_LOG(LogTemp, Warning, TEXT("Pickup BeginPlay: %s, WeaponClass=%s"),
        *GetName(),
        WeaponClass ? *WeaponClass->GetName() : TEXT("None"));

    if (PickUpCollision)
    {
        PickUpCollision->OnComponentBeginOverlap.AddDynamic(
            this, &AWeaponPickUp::OnPickupOverlap);
    }

    if (!WeaponClass)
    {
        UE_LOG(LogTemp, Warning, TEXT("Pickup: WeaponClass is NONE"));
        return;
    }

    AWeaponActor* DefaultWeapon = WeaponClass->GetDefaultObject<AWeaponActor>();
    if (!DefaultWeapon)
    {
        UE_LOG(LogTemp, Warning, TEXT("Pickup: DefaultWeapon is nullptr"));
        return;
    }

    
    USkeletalMeshComponent* WeaponMeshComp = DefaultWeapon->GetWeaponMesh();
    if (WeaponMeshComp && PickUpMesh)
    {
        if (PickUpMesh)
        {
            PickUpMesh->SetSkeletalMesh(WeaponMeshComp->GetSkeletalMeshAsset());

            PickUpMesh->SetRelativeLocation(FVector::ZeroVector);
            
            PickUpMesh->SetRelativeScale3D(WeaponMeshComp->GetRelativeScale3D());

            const FRotator SrcRot = WeaponMeshComp->GetRelativeRotation();

            FRotator TiltedRot(TiltPitch, SrcRot.Yaw, TiltRoll);

            PickUpMesh->SetRelativeRotation(TiltedRot);
        }
    }

    UNiagaraComponent* NiagaraComp = DefaultWeapon->GetNiagaraComp();
    if (NiagaraComp && PickUpNiagara)
    {
        if (PickUpNiagara)
        {

            PickUpNiagara->SetAsset(NiagaraComp->GetAsset());

            PickUpNiagara->SetRelativeLocation(NiagaraComp->GetRelativeLocation());
            PickUpNiagara->SetRelativeRotation(NiagaraComp->GetRelativeRotation());
            PickUpNiagara->SetRelativeScale3D(NiagaraComp->GetRelativeScale3D());

            PickUpNiagara->Activate(true);
        }
    }

    else
    {
        UE_LOG(LogTemp, Warning,
            TEXT("Pickup: Niagara is nullptr (WeaponNiagara=%s, PickUpNiagara=%s)"),
            NiagaraComp ? TEXT("Valid") : TEXT("Null"),
            PickUpNiagara ? TEXT("Valid") : TEXT("Null"));
    }
   


}

// Called every frame
void AWeaponPickUp::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);

    //í¡ì… ì¤‘ì´ë¼ë©´: í”Œë ˆì´ì–´ ìª½ìœ¼ë¡œ ë¹¨ë ¤ë“¤ì–´ê°€ëŠ” ì²˜ë¦¬ë§Œ ìˆ˜í–‰
    if (bIsAbsorbing)
    {
        // íƒ€ê²Ÿì´ ìœ íš¨í•œì§€ ì²´í¬
        if (!TargetCharacter.IsValid())
        {
            Destroy();
            return;
        }

        // ì§„í–‰ ì‹œê°„ ì¦ê°€
        AbsorbElapsedTime += DeltaTime;

        // 0~1 ì‚¬ì´ì˜ ì§„í–‰ë„
        float Alpha = 0.0f;
        if (AbsorbDuration > 0.0f)
        {
            Alpha = AbsorbElapsedTime / AbsorbDuration;
        }
        Alpha = FMath::Clamp(Alpha, 0.0f, 1.0f);

        // ëª©í‘œ ìœ„ì¹˜ = ìºë¦­í„° ìœ„ì¹˜ + ì˜¤í”„ì…‹
        FVector TargetLocation = TargetCharacter->GetActorLocation();
        TargetLocation.Z += AbsorbHeightOffset;

        // ìœ„ì¹˜ Lerp
        FVector AbsorbLocation = FMath::Lerp(AbsorbStartLocation, TargetLocation, Alpha);
        SetActorLocation(AbsorbLocation);

        // ìŠ¤ì¼€ì¼ ì¤„ì´ê¸°
        float NewScaleValue = FMath::Lerp(1.0f, 0.0f, Alpha);
        SetActorScale3D(FVector(NewScaleValue));

        // ì™„ë£Œë˜ë©´ ì•„ì´í…œ ì§€ê¸‰ í›„ ì‚­ì œ
        if (Alpha >= 1.0f)
        {
            if (TargetCharacter.IsValid())
            {
                TargetCharacter->OnPickUpEnhancedWeapon(this);
            }

            Destroy();
        }

        return; //í¡ì… ì¤‘ì´ë©´ ì•„ë˜ ë– ë‹¤ë‹ˆê¸°/íšŒì „ ë¡œì§ ê±´ë„ˆë›°ê¸°
    }


    //í¡ì… ì¤‘ì´ ì•„ë‹ ë•ŒëŠ” "ë§ˆí¬ ì•„ì´í…œ" ìŠ¤íƒ€ì¼ë¡œ ë‘¥ë‘¥ ë– ë‹¤ë‹ˆê³  íšŒì „

    RunningTime += DeltaTime;

    float OffsetZ = FMath::Sin(RunningTime * BobSpeed) * BobAmplitude;

    FVector FloatLocation = StartLocation;
    FloatLocation.Z = StartLocation.Z + OffsetZ;
    SetActorLocation(FloatLocation);

    FRotator Rot = GetActorRotation();
    Rot.Yaw += RotationSpeed * DeltaTime;
    Rot.Pitch = 0.0f;
    Rot.Roll = 0.0f;
    SetActorRotation(Rot);
}

void AWeaponPickUp::RefreshVisualFromWeaponClass()
{
    if (!WeaponClass)
    {
        UE_LOG(LogTemp, Warning, TEXT("Pickup: WeaponClass is NONE in RefreshVisualFromWeaponClass"));
        return;
    }

    AWeaponActor* DefaultWeapon = WeaponClass->GetDefaultObject<AWeaponActor>();
    if (!DefaultWeapon)
    {
        UE_LOG(LogTemp, Warning, TEXT("Pickup: DefaultWeapon is nullptr"));
        return;
    }

    // ğŸ”¸ ë¬´ê¸° ë©”ì‰¬ ë³µì‚¬
    USkeletalMeshComponent* WeaponMeshComp = DefaultWeapon->GetWeaponMesh();
    if (WeaponMeshComp && PickUpMesh)
    {
        PickUpMesh->SetSkeletalMesh(WeaponMeshComp->GetSkeletalMeshAsset());

        PickUpMesh->SetRelativeLocation(FVector::ZeroVector);
        PickUpMesh->SetRelativeScale3D(WeaponMeshComp->GetRelativeScale3D());

        const FRotator SrcRot = WeaponMeshComp->GetRelativeRotation();
        FRotator TiltedRot(TiltPitch, SrcRot.Yaw, TiltRoll);
        PickUpMesh->SetRelativeRotation(TiltedRot);
    }

    // ğŸ”¸ ë‚˜ì´ì•„ê°€ë¼ ë³µì‚¬
    UNiagaraComponent* NiagaraComp = DefaultWeapon->GetNiagaraComp();
    if (NiagaraComp && PickUpNiagara)
    {
        PickUpNiagara->SetAsset(NiagaraComp->GetAsset());
        PickUpNiagara->SetRelativeLocation(NiagaraComp->GetRelativeLocation());
        PickUpNiagara->SetRelativeRotation(NiagaraComp->GetRelativeRotation());
        PickUpNiagara->SetRelativeScale3D(NiagaraComp->GetRelativeScale3D());
        PickUpNiagara->Activate(true);
    }
    else
    {
        UE_LOG(LogTemp, Warning,
            TEXT("Pickup: Niagara is nullptr (WeaponNiagara=%s, PickUpNiagara=%s)"),
            NiagaraComp ? TEXT("Valid") : TEXT("Null"),
            PickUpNiagara ? TEXT("Valid") : TEXT("Null"));
    }
}
